require_relative '../../../lib/community/app_handler'

# Basic certification tests for the Flower SuperNode appliance.
#
# The SuperNode runs a Flower client (container: flower-supernode) inside a
# Docker container managed by systemd (unit: flower-supernode.service). It
# DIALS OUT to the SuperLink Fleet API and publishes NO inbound ports, so there
# is no listening port to assert -- only the systemd unit, the running
# container and the service report are checked.
#
# For standalone certification the appliance is given a loopback SuperLink
# placeholder (ONEAPP_FL_SUPERLINK_ADDRESS=127.0.0.1:9092) with TLS disabled.
# With ONEAPP_FL_MAX_RETRIES=0 (unlimited) and --restart unless-stopped the
# container stays running while it retries the unreachable coordinator, so the
# checks below hold even without a real SuperLink. A real deployment supplies
# the actual SuperLink address (or OneGate discovery) via the OneFlow service.
describe 'Appliance Certification' do
    include_context('vm_handler')

    # First boot installs/starts Docker, may lazily build the framework image,
    # creates and starts the container. Allow a generous window for the main
    # unit to report 'active'.
    it 'flower-supernode service is active' do
        cmd = 'systemctl is-active flower-supernode.service'
        start_time = Time.now
        timeout = 600

        result = nil
        loop do
            result = @info[:vm].ssh(cmd)
            break if result.stdout.strip == 'active'

            if Time.now - start_time > timeout
                raise "flower-supernode.service did not become active within #{timeout}s " \
                      "(last status: '#{result.stdout.strip}')"
            end

            sleep 10
        end

        expect(result.stdout.strip).to eq('active')
    end

    # Docker must be installed and its daemon active -- the SuperNode runs
    # entirely inside a Docker container.
    it 'docker service is running' do
        result = @info[:vm].ssh('systemctl is-active docker')
        expect(result.stdout.strip).to eq('active')
    end

    # The container named flower-supernode must be present and running.
    # service_bootstrap creates it with --restart unless-stopped and starts it
    # via systemd, then waits for State.Running=true.
    it 'flower-supernode container is running' do
        cmd = "docker inspect -f '{{.State.Running}}' flower-supernode"
        start_time = Time.now
        timeout = 120

        result = nil
        loop do
            result = @info[:vm].ssh(cmd)
            break if result.success? && result.stdout.strip == 'true'

            if Time.now - start_time > timeout
                raise "flower-supernode container not running within #{timeout}s " \
                      "(last output: '#{result.stdout.strip}')"
            end

            sleep 5
        end

        expect(result.stdout.strip).to eq('true')
    end

    # The systemd unit file generated by service_configure must exist.
    it 'flower-supernode systemd unit file exists' do
        result = @info[:vm].ssh('test -f /etc/systemd/system/flower-supernode.service')
        expect(result.exitstatus).to eq(0)
    end

    # service_configure writes the service report to ONE_SERVICE_REPORT, which
    # the one-apps framework sets to /etc/one-appliance/config.
    it 'service report file exists' do
        result = @info[:vm].ssh('sudo test -f /etc/one-appliance/config')
        expect(result.exitstatus).to eq(0)
    end

    # Verify the framework signalled readiness via the standard MOTD marker.
    it 'check oneapps motd' do
        cmd = 'cat /etc/motd'

        max_retries = 30
        sleep_time = 10
        expected_motd = 'All set and ready to serve'

        execution = nil
        max_retries.times do |attempt|
            execution = @info[:vm].ssh(cmd)
            break if execution.stdout.include?(expected_motd)

            puts "Attempt #{attempt + 1}/#{max_retries}: Waiting for MOTD to update..."
            sleep sleep_time
        end

        expect(execution.exitstatus).to eq(0)
        expect(execution.stdout).to include(expected_motd)
    end
end
