# context version definition
VERSION := 6.10.0
RELEASE := 2

# log
VERBOSE         := 1
PACKER_LOG      := 0
PACKER_HEADLESS := true

SERVICES := service_Lithops service_UERANSIM capone131

.DEFAULT_GOAL := help

# default directories
DIR_ONEAPPS := ../one-apps
DIR_BUILD   := build
DIR_EXPORT  := export
$(shell mkdir -p ${DIR_BUILD} ${DIR_EXPORT})

# don't delete exported
.SECONDARY: $(patsubst %,$(DIR_EXPORT)/%.qcow2,$(SERVICES))

# logging func
INFO=sh -c 'if [ $(VERBOSE) = 1 ]; then echo [INFO] $$1; fi' INFO

# export all variables
export
