require_relative '../../../lib/community/app_handler'

# Basic certification tests for the Flower SuperLink appliance.
#
# The SuperLink runs the flower-superlink gRPC coordinator inside a Docker
# container managed by systemd (unit: flower-superlink.service, container:
# flower-superlink). The Fleet API is published on the VM's primary NIC at
# port 9092 for SuperNode connections; the Control API is bound to 127.0.0.1
# only and is therefore intentionally NOT probed here.
#
# These checks only assert what appliance-superlink.sh guarantees on a
# successful boot. The boot installs Docker, pulls flwr/superlink, generates
# TLS certs, writes the systemd unit and starts the service.
describe 'Appliance Certification' do
    include_context('vm_handler')

    # First boot pulls/starts Docker, optionally regenerates TLS certs and
    # starts the container, so allow a generous window for the main unit to
    # come up. systemctl is-active returns 'active' once the container is
    # running under systemd.
    it 'flower-superlink service is active' do
        cmd = 'systemctl is-active flower-superlink.service'
        start_time = Time.now
        timeout = 600

        result = nil
        loop do
            result = @info[:vm].ssh(cmd)
            break if result.stdout.strip == 'active'

            if Time.now - start_time > timeout
                raise "flower-superlink.service did not become active within #{timeout}s " \
                      "(last status: '#{result.stdout.strip}')"
            end

            sleep 10
        end

        expect(result.stdout.strip).to eq('active')
    end

    # Docker must be installed and its daemon active -- the SuperLink runs
    # entirely inside a Docker container.
    it 'docker service is running' do
        result = @info[:vm].ssh('systemctl is-active docker')
        expect(result.stdout.strip).to eq('active')
    end

    # The container named flower-superlink must be present and running.
    it 'flower-superlink container is running' do
        cmd = "docker inspect -f '{{.State.Running}}' flower-superlink"
        start_time = Time.now
        timeout = 120

        result = nil
        loop do
            result = @info[:vm].ssh(cmd)
            break if result.success? && result.stdout.strip == 'true'

            if Time.now - start_time > timeout
                raise "flower-superlink container not running within #{timeout}s " \
                      "(last output: '#{result.stdout.strip}')"
            end

            sleep 5
        end

        expect(result.stdout.strip).to eq('true')
    end

    # The Fleet API is published on the VM's primary NIC at 9092 for SuperNode
    # connections. Probe that a socket is listening on port 9092 (any address);
    # the bind is to the primary IP, not localhost, so match the port column.
    it 'fleet API port 9092 is listening' do
        cmd = "ss -ltn '( sport = :9092 )' | grep -q ':9092' && echo LISTENING"
        start_time = Time.now
        timeout = 180

        result = nil
        loop do
            result = @info[:vm].ssh(cmd)
            break if result.stdout.include?('LISTENING')

            if Time.now - start_time > timeout
                raise "Fleet API port 9092 not listening within #{timeout}s"
            end

            sleep 5
        end

        expect(result.stdout).to include('LISTENING')
    end

    # The systemd unit file generated by service_configure must exist.
    it 'flower-superlink systemd unit file exists' do
        result = @info[:vm].ssh('test -f /etc/systemd/system/flower-superlink.service')
        expect(result.exitstatus).to eq(0)
    end

    # service_configure writes the service report to ONE_SERVICE_REPORT, which
    # the one-apps framework sets to /etc/one-appliance/config.
    it 'service report file exists' do
        result = @info[:vm].ssh('sudo test -f /etc/one-appliance/config')
        expect(result.exitstatus).to eq(0)
    end

    # Verify the framework signalled readiness via the standard MOTD marker.
    it 'check oneapps motd' do
        cmd = 'cat /etc/motd'

        max_retries = 30
        sleep_time = 10
        expected_motd = 'All set and ready to serve'

        execution = nil
        max_retries.times do |attempt|
            execution = @info[:vm].ssh(cmd)
            break if execution.stdout.include?(expected_motd)

            puts "Attempt #{attempt + 1}/#{max_retries}: Waiting for MOTD to update..."
            sleep sleep_time
        end

        expect(execution.exitstatus).to eq(0)
        expect(execution.stdout).to include(expected_motd)
    end
end
